name: nqetools
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.13
  - pip
  - pytest
  - numpy
  - scipy
  - pandas
  - matplotlib
  - opt_einsum
  - jax
  - jaxlib
  - ml_dtypes
  - sympy
  - pyfftw
  - chemiscope
  - jupyterlab
  - ase
  - sella
  - pyfftw
  - ipi
  - py-plumed
  - pip:
    - torch-gpu
    - mace-torch
    - cuequivariance
    - cuequivariance-torch
    - cuequivariance-ops-torch-cu12
    - git+https://github.com/LouieSlocombe/geodesic_interpolate.git
