from setuptools import setup, find_packages

setup(
    name='nqetools',
    version='0.1.0',
    author='Louie Slocombe',
    author_email='louies@hotmail.co.uk',
    description='A centralised set of tools for doing nuclear quantum calculations.',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url='https://github.com/LouieSlocombe/nqetools',
    packages=find_packages(include=['nqetools', 'nqetools.*']),
    package_data={
        'nqetools': [
            'templates/*',
            'thermostats/*',
            'opes/*',
        ],
    },
    include_package_data=True,
    classifiers=[
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.13',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
        'Intended Audience :: Science/Research',
        'Topic :: Scientific/Engineering :: Chemistry',
        'Topic :: Scientific/Engineering :: Physics',
    ],
    python_requires='>=3.13',
    install_requires=[
        'numpy',
        'scipy',
        'pandas',
        'matplotlib',
        'opt_einsum',
        'jax',
        'jaxlib',
        'ml_dtypes',
        'sympy',
        'pyfftw',
        'chemiscope',
        'ase',
        'i-pi',
        'py-plumed',
        'openmm',
        'openmm-ml',
        'torch',
        'nnpops',
        'openmm-torch',
        'openmmforcefields',
        'openmmtools',
        'ambertools',
        'pdbfixer',
        'rdkit',
        'mdanalysis',
        'mace-torch',
        'sella',
        'geodesic_interpolate @ git+https://github.com/LouieSlocombe/geodesic_interpolate.git',
    ],
    extras_require={
        'test': [
            'pytest',
        ],
        'dev': [
            'jupyterlab',
            'pytest',
        ],
        'notebook': [
            'jupyterlab',
        ]
    },
)
